apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mojaloop-payment-manager.fullname" . }}-keycloak-realm
data:
  realm.json: |-
{{ default (tpl (.Files.Get "conf/keycloak-realm.json.tpl") $) .Values.keycloak.realmConfig | indent 4 }}
