apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pm4ml-mojaloop-connector.fullname" . }}-jws-public-keys
  labels:
    app.kubernetes.io/name: {{ include "pm4ml-mojaloop-connector.fullname" . }}-jws-public-keys
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: "{{ $.Chart.AppVersion }}"
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
data:
  {{- range $name, $data := .Values.sharedJWSPubKeys }}
  {{ $name }}.pem: |-
{{ $data | indent 4 }}
  {{- end }}
